name: Update Yandex Feed Automatically

on:
  # Запуск по расписанию (каждый день в 03:00 UTC)
  schedule:
    - cron: '0 3 * * *'
  # Ручной запуск из интерфейса GitHub
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    
    # Права для записи в репозиторий
    permissions:
      contents: write
      
    steps:
      # Шаг 1: Получение кода репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Токен для работы с репозиторием

      # Шаг 2: Генерация или обновление XML-фида
      - name: Generate Yandex Feed
        run: |
          # Пример генерации XML (замените на свои команды!)
          cat << 'EOF' > yandex-feed.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <yml_catalog date="$(date +'%Y-%m-%d %H:%M')">
            <shop>
              <name>Example Shop</name>
              <offers>
                <offer id="1">
                  <name>Test Product</name>
                  <price>1000</price>
                </offer>
              </offers>
            </shop>
          </yml_catalog>
          EOF

          # Проверка XML на валидность (опционально)
          xmllint --noout yandex-feed.xml || exit 1

      # Шаг 3: Коммит и отправка изменений
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@users.noreply.github.com"
          
          git add yandex-feed.xml
          
          # Коммит только если есть изменения
          if git diff --quiet --exit-code; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Auto-update Yandex feed [skip ci]"
            git push
          fi

      # Шаг 4: Уведомление об ошибке (опционально)
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚨 **Feed update failed!** Check [Action logs](${github.server_url}/${github.repository}/actions/runs/${github.run_id})'
            })
